title: Page

fields:
  title:
    label: Title
    type:  text

  description:
    label: Description
    type:  textarea

  contact_links:
    label: Contact Links
    type:  textarea

  contact_form_text:
    label: Contact Form text
    type: textarea