title: Page

fields:
  title:
    label: Title
    type:  text

  description:
    label: Description
    type:  markdown

  meta_image:
    label: >
      Meta image <i style="font-weight: normal;">(Shows when you <a href="https://css-tricks.com/essential-meta-tags-social-media/" target="_blank" style="text-decoration: underline;">share a link of the site on social media</a>)</i>
    type:  image

  contact_links:
    label: Contact Links
    type:  markdown

  contact_form_text:
    label: Contact Form text
    type: markdown